site_name: TFT_eSPI library
site_description: Some docs to help you to use the TFT_eSPI library.
# site_url:
repo_url: https://github.com/Marcussacapuces91/doc-TFT_eSPI
copyright: 'Copyright &copy; 2024 by Marc SIBERT'
# google_analytics: ['config', 'G-7TCN59P65X']

theme:
  name: readthedocs
  highlightjs: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      pygments_lang_class: true
      use_pygments: false
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tilde

nav:
  - 'Welcome': index.md
  - 'Getting Started': starting.md
  - 'Display Fundamentals': fundamentals.md
  - 'Graphics and UI': graphics.md
  - 'Touch and Input': inputs.md
  - 'Advanced Topics': advanced.md
  - 'Examples and Resources': examples.md
  - 'Header file TFT_eSPI.h':
    - 'File content': tft_espi/index.md
    - Colors: tft_espi/colors.md
    - Datums: tft_espi/datums.md
    - Classes:
      - tft_espi/class.md
      - tft_espi_button/class.md
    - Public methods:
      - tft_espi/methods/constructor.md
      - tft_espi/methods/begin.md
      - tft_espi/methods/drawarc.md
      - tft_espi/methods/drawbitmap.md
      - tft_espi/methods/drawcentrestring.md
      - tft_espi/methods/drawcircle.md
      - tft_espi/methods/drawchar.md
      - tft_espi/methods/drawfastline.md
      - tft_espi/methods/drawline.md
      - tft_espi/methods/drawpixel.md
      - tft_espi/methods/drawrect.md
      - tft_espi/methods/drawstring.md
      - tft_espi/methods/drawtriangle.md
      - tft_espi/methods/fillcircle.md
      - tft_espi/methods/fillrect.md
      - tft_espi/methods/fillscreen.md
      - tft_espi/methods/filltriangle.md
      - tft_espi/methods/gettextdatum.md
      - tft_espi/methods/gettextpadding.md
      - tft_espi/methods/height_width.md
      - tft_espi/methods/init.md
      - tft_espi/methods/print.md
      - tft_espi/methods/readpixel.md
      - tft_espi/methods/setcursor.md
      - tft_espi/methods/setrotation.md
      - tft_espi/methods/settextcolor.md
      - tft_espi/methods/settextdatum.md
      - tft_espi/methods/settextfont.md
      - tft_espi/methods/settextpadding.md
      - tft_espi/methods/settextsize.md
      - tft_espi/methods/settextwrap.md
      - tft_espi/methods/setviewport.md
  - 'Header file TFT_eSPI_Button.h':
    - Class: tft_espi_button/class.md
    - Public methods:
        - tft_espi_button/constructor.md
  - 'Header file TFT_eSPRITE.h':
    - Class: tft_esprite.md

# Only mkdocs >= 1.6
exclude_docs: |
  getsettextdatum.md
  getsettextpadding.md
  helloword.md
  button.md
