site_name: TFT_eSPI library
site_description: Some docs to help you to use the TFT_eSPI library.
# site_url:
repo_url: https://github.com/Marcussacapuces91/doc-TFT_eSPI
copyright: 'Copyright &copy; 2024 by Marc SIBERT'

theme:
  name: readthedocs
  highlightjs: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      pygments_lang_class: true
      use_pygments: false
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tilde

nav:
  - 'Welcome': index.md
  - 'Getting Started': starting.md
  - 'Display Fundamentals': fundamentals.md
  - 'Graphics and UI': graphics.md
  - 'Touch and Input': inputs.md
  - 'Advanced Topics': advanced.md
  - 'Examples and Resources': examples.md
  - TFT_eSPI:
    - Class: tft_espi/class.md
    - Methods:
      - tft_espi/methods/constructor.md
      - tft_espi/methods/begin.md
      - tft_espi/methods/drawchar.md
      - tft_espi/methods/drawfastline.md
      - tft_espi/methods/drawline.md
      - tft_espi/methods/drawpixel.md
      - tft_espi/methods/fillrect.md
      - tft_espi/methods/height_width.md
      - tft_espi/methods/init.md
      - tft_espi/methods/setviewport.md
  - TFT_eSPRITE:
    - Class: tft_esprite.md
