[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TFT_eSPI "
authors = [{name = "Marc SIBERT", email = "marc@sibert.fr"}]
dynamic = ["version", "description"]
